### ISSUE TITLE
The point of Boxed<T>

### ISSUE THREAD

**Issue by darksv** [michalpogodakotwica/Sleipnir#1]
Hi! First of all, I want to say I really like your project! Looking through the source code I noticed that you created `Boxed<T>` class. I can't figure out what is the purpose of this class. It has only one field and no properties nor methods. Wouldn't it be better to use the value from this field directly in place of your class?

**Comment by michalpogodakotwica** [comment]
Thanks.
It wraps value type (struct) with reference to it. It is used inside another value type and thanks to it I can use the wrapped object more like a class than a struct - I can make changes in wrapped type without reassigning whole wrapping struct. It can be a little confusing but I find it more convenient. I'll add a comment for it later.
